iceOne_Cloud/Models/ErrorViewModel.cs
namespace iceOne_Cloud.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

iceOne_Cloud/Models/bnbDB.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace iceOne_Cloud.Models
{
    public class bnbDB
    {
        public int Id { get; set; }
        public string? Name { get; set; }

        public double Price { get; set; }
        public string? Address { get; set; }
        public string? contactEmail { get; set; }
    }
}

iceOne_Cloud/Models/seedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using iceOne_Cloud.Data;
using System;
using System.Linq;

namespace iceOne_Cloud.Models
{
    public class seedData
    {
        public static void Initialize(IServiceProvider serviceProvider) 
        {
            using (var context = new iceOne_CloudContext(
            serviceProvider.GetRequiredService<
                DbContextOptions<iceOne_CloudContext>>())) 
            {
                if (context.bnbDB.Any())
                {
                    return;   // DB has been seeded
                }
                context.bnbDB.AddRange(
                    new bnbDB
                    {
                       
                        Name = "The Swallows",
                        Address="25 pickUr lane",
                        contactEmail="pickUr@gmail.com",
                        Price=500.99,
                    }

                    ); 
                context.SaveChanges();
            }
        }     
    }
}

iceOne_Cloud/Controllers/HomeController.cs
using iceOne_Cloud.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace iceOne_Cloud.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult CalcPay()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

iceOne_Cloud/Controllers/bnbDBsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using iceOne_Cloud.Data;
using iceOne_Cloud.Models;

namespace iceOne_Cloud.Controllers
{
    public class bnbDBsController : Controller
    {
        private readonly iceOne_CloudContext _context;

        public bnbDBsController(iceOne_CloudContext context)
        {
            _context = context;
        }


        // GET: bnbDBs
        public async Task<IActionResult> Index()
        {
            return View(await _context.bnbDB.ToListAsync());
        }

        // GET: bnbDBs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bnbDB = await _context.bnbDB
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bnbDB == null)
            {
                return NotFound();
            }

            return View(bnbDB);
        }

        // GET: bnbDBs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: bnbDBs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Address,contactEmail")] bnbDB bnbDB)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bnbDB);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bnbDB);
        }

        // GET: bnbDBs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bnbDB = await _context.bnbDB.FindAsync(id);
            if (bnbDB == null)
            {
                return NotFound();
            }
            return View(bnbDB);
        }

        // POST: bnbDBs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,Address,contactEmail")] bnbDB bnbDB)
        {
            if (id != bnbDB.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bnbDB);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!bnbDBExists(bnbDB.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bnbDB);
        }

        // GET: bnbDBs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bnbDB = await _context.bnbDB
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bnbDB == null)
            {
                return NotFound();
            }

            return View(bnbDB);
        }

    
        // POST: bnbDBs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bnbDB = await _context.bnbDB.FindAsync(id);
            if (bnbDB != null)
            {
                _context.bnbDB.Remove(bnbDB);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool bnbDBExists(int id)
        {
            return _context.bnbDB.Any(e => e.Id == id);
        }
    }
}

iceOne_Cloud/Views/Home/CalcPay.cshtml
@{
    ViewData["Title"] = "Cost Calculator";
}
<h1>@ViewData["Title"]</h1>

<p>Enter the price of the place and the number of day staying below</p>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Decimal Multiplier</title>
</head>
<body>
    <input type="number" step="any" id="decimalInput" placeholder="Enter a Price of room">
    <input type="number" id="spinInput" placeholder="Enter a number of days">
    <button onclick="multiplyDecimal()">Multiply</button>
    <p id="result"></p>

    <script>
        function multiplyDecimal() {
            var decimalValue = parseFloat(document.getElementById("decimalInput").value);
            var spinValue = parseInt(document.getElementById("spinInput").value);
            var result = decimalValue * spinValue;
            document.getElementById("result").innerText = "Total Cost of your stay: R " + result;
        }
    </script>
</body>

iceOne_Cloud/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>To BnB for cheap, where we offer you the cheapest places to stay in Durban</a></p>
</div>

iceOne_Cloud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iceOne_Cloud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/iceOne_Cloud.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">iceOne_Cloud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="bnbDBs"asp-action="">BnB Database</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CalcPay">Calculate Cost</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - iceOne_Cloud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

iceOne_Cloud/Views/bnbDBs/Create.cshtml
@model iceOne_Cloud.Models.bnbDB

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>bnbDB</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="contactEmail" class="control-label"></label>
                <input asp-for="contactEmail" class="form-control" />
                <span asp-validation-for="contactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

iceOne_Cloud/Views/bnbDBs/Delete.cshtml
@model iceOne_Cloud.Models.bnbDB

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>bnbDB</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.contactEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.contactEmail)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

iceOne_Cloud/Views/bnbDBs/Details.cshtml
@model iceOne_Cloud.Models.bnbDB

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>bnbDB</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.contactEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.contactEmail)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

iceOne_Cloud/Views/bnbDBs/Edit.cshtml
@model iceOne_Cloud.Models.bnbDB

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>bnbDB</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="contactEmail" class="control-label"></label>
                <input asp-for="contactEmail" class="form-control" />
                <span asp-validation-for="contactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

iceOne_Cloud/Views/bnbDBs/Index.cshtml
@model IEnumerable<iceOne_Cloud.Models.bnbDB>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.contactEmail)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.contactEmail)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>